# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermepa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermeparesponse',
            name='id_TPV',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sermepa.SermepaIdTPV'),
        ),
        migrations.AlterField(
            model_name='sermepaidtpv',
            name='idtpv',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
